src/Siwapp/OrderBundle/Entity/Order.php
<?php
/**
 * Created by PhpStorm.
 * User: jvasquez
 * Date: 13/1/2017
 * Time: 5:06 PM
 */

namespace Siwapp\OrderBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Inflector\Inflector;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Doctrine\ORM\Event\PreUpdateEventArgs;
use Siwapp\CoreBundle\Entity\AbstractInvoice;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Siwapp\OrderBundle\Entity\Order
 *
 * @ORM\Table(name="`order`", indexes={
 *    @ORM\Index(name="order_cstnm_idx", columns={"customer_name"}),
 *    @ORM\Index(name="order_cstid_idx", columns={"customer_identification"}),
 *    @ORM\Index(name="order_cstml_idx", columns={"customer_email"}),
 *    @ORM\Index(name="order_cntct_idx", columns={"contact_person"})
 * })
 * @ORM\Entity(repositoryClass="Siwapp\OrderBundle\Repository\OrderRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Order extends AbstractInvoice
{
    /**
     * @ORM\ManyToMany(targetEntity="Siwapp\CoreBundle\Entity\Item", cascade={"all"}, inversedBy="order")
     * @ORM\JoinTable(name="orders_items",
     *      joinColumns={@ORM\JoinColumn(name="order_id", referencedColumnName="id", onDelete="CASCADE")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="item_id", referencedColumnName="id", unique=true, onDelete="CASCADE")}
     * )
     * @Assert\NotBlank()
     */
    protected $items;

    /**
     * @var integer $number
     *
     * @ORM\Column(name="number", type="integer", nullable=true)
     */
    private $number;

    /**
     * @var boolean $imported
     *
     * @ORM\Column(type="boolean")
     */
    private $imported = false;

    /**
     * @var boolean $sent_by_email
     *
     * @ORM\Column(name="sent_by_email", type="boolean", nullable=true)
     */
    private $sent_by_email;

    /**
     * @var date $issue_date
     *
     * @ORM\Column(name="issue_date", type="date", nullable=true)
     * @Assert\Date()
     */
    private $issue_date;

    /**
     * @var integer
     *
     * @ORM\Column(name="estimate_to", type="bigint", nullable=true)
     */
    private $estimate_to;
    
    /**
     * @var string
     *
     * @ORM\Column(name="postal_code", type="string", length=10, nullable=true)
     */
    private $postalCode;
    
    /**
     * @var string
     *
     * @ORM\Column(name="location", type="string", length=255, nullable=true)
     */
    private $location;
    
    /**
     * @var string
     *
     * @ORM\Column(name="province", type="string", length=255, nullable=true)
     */
    private $province;
    
    /**
     * @var string
     *
     * @ORM\Column(name="mandato", type="string", nullable=true, length=10)
     */
    private $mandato;
    
    /**
     * @var date $fecha_mandato
     *
     * @ORM\Column(name="fecha_mandato", type="date", nullable=true)
     * @Assert\Date()
     */
    private $fecha_mandato;
    
    /**
     * @var string
     *
     * @ORM\Column(name="bic", type="string", nullable=true, length=11)
     */
    private $bic;
    
    /**
     * @var string
     *
     * @ORM\Column(name="iban", type="string", nullable=true, length=100)
     */
    private $iban;

    public function __construct()
    {
        parent::__construct();
        $this->issue_date = new \DateTime();
    }

    /**
     * Set draft
     *
     * @param boolean $draft
     */
    public function setDraft($draft)
    {
        $this->draft = $draft;
    }

    /**
     * Get draft
     *
     * @return boolean
     */
    public function isDraft()
    {
        return $this->status == self::DRAFT;
    }

    /**
     * @return boolean
     */
    public function isPending()
    {
        return $this->status == self::PENDING;
    }

    /**
     * @return boolean
     */
    public function isApproved()
    {
        return $this->status == self::APPROVED;
    }

    /**
     * Set number
     *
     * @param integer $number
     */
    public function setNumber($number)
    {
        $this->number = $number;
    }

    /**
     * Get number
     *
     * @return integer
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Set sent_by_email
     *
     * @param boolean $sentByEmail
     */
    public function setSentByEmail($sentByEmail)
    {
        $this->sent_by_email = $sentByEmail;
    }

    /**
     * Get sent_by_email
     *
     * @return boolean
     */
    public function isSentByEmail(): bool
    {
        return (bool) $this->sent_by_email;
    }

    /**
     * Set issue_date
     *
     * @param date $issueDate
     */
    public function setIssueDate($issueDate)
    {
        $this->issue_date = $issueDate instanceof \DateTime ?
            $issueDate: new \DateTime($issueDate);
    }

    /**
     * Get issue_date
     *
     * @return date
     */
    public function getIssueDate()
    {
        return $this->issue_date;
    }

    /**
     * @return bool
     */
    public function isImported(): bool
    {
        return $this->imported;
    }

    /**
     * @param bool $imported
     */
    public function setImported(bool $imported)
    {
        $this->imported = $imported;
    }

    /**
     * @return int
     */
    public function getEstimateTo(): int
    {
        return $this->estimate_to;
    }

    /**
     * @param int $estimate_to
     */
    public function setEstimateTo(int $estimate_to)
    {
        $this->estimate_to = $estimate_to;
    }
    
    /**
     * Set postalCode
     *
     * @param string $postalCode
     *
     * @return Customer
     */
    public function setPostalCode($postalCode)
    {
        $this->postalCode = $postalCode;
        
        return $this;
    }
    
    /**
     * Get postalCode
     *
     * @return string
     */
    public function getPostalCode()
    {
        return $this->postalCode;
    }
    
    /**
     * Set location
     *
     * @param string $location
     *
     * @return Customer
     */
    public function setLocation($location)
    {
        $this->location = $location;
        
        return $this;
    }
    
    /**
     * Get location
     *
     * @return string
     */
    public function getLocation()
    {
        return $this->location;
    }
    
    /**
     * Set province
     *
     * @param string $province
     *
     * @return Customer
     */
    public function setProvince($province)
    {
        $this->province = $province;
        
        return $this;
    }
    
    /**
     * Get province
     *
     * @return string
     */
    public function getProvince()
    {
        return $this->province;
    }
    
    /**
     * Set mandato
     *
     * @param string $mandato
     *
     * @return Customer
     */
    public function setMandato($mandato)
    {
        $this->mandato = $mandato;
        
        return $this;
    }
    
    /**
     * Get mandato
     *
     * @return string
     */
    public function getMandato()
    {
        return $this->mandato;
    }
    
    /**
     * Set fecha_mandato
     *
     * @param date $fechaMandato
     */
    public function setFechaMandato($fechaMandato)
    {
        $this->fecha_mandato = $fechaMandato instanceof \DateTime ?
        $fechaMandato : new \DateTime($fechaMandato);
    }
    
    /**
     * Get fecha_mandato
     *
     * @return date
     */
    public function getFechaMandato()
    {
        return $this->fecha_mandato;
    }
    
    /**
     * Set bic
     *
     * @param string $bic
     *
     * @return Customer
     */
    public function setBic($bic)
    {
        $this->bic = $bic;
        
        return $this;
    }
    
    /**
     * Get bic
     *
     * @return string
     */
    public function getBic()
    {
        return $this->bic;
    }
    
    /**
     * Set iban
     *
     * @param string $iban
     *
     * @return Customer
     */
    public function setIban($iban)
    {
        $this->iban = $iban;
        
        return $this;
    }
    
    /**
     * Get iban
     *
     * @return string
     */
    public function getIban()
    {
        return $this->iban;
    }

    /** ********** CUSTOM METHODS AND PROPERTIES ************* */


    /**
     * try to catch custom methods to be used in twig templates
     */
    public function __get($name)
    {
        $method = Inflector::camelize("get_{$name}");
        if (method_exists($this, $method)) {
            return $this->$method();
        }
        return false;
    }

    public function __isset($name)
    {
        if (in_array($name, array_keys(get_object_vars($this)))) {
            return true;
        }

        return parent::__isset($name);
    }

    public function __toString()
    {
        return $this->label();
    }

    public function label()
    {
        /*$series = $this->getSeries();
        $label = '';
        $label .= $series ? $series->getValue() : '';
        $label .= $this->isDraft() ? '[draft]' : $this->getNumber();*/
        $series = $this->getSeries();
        $label = '';
        $label .= $series ? $series->getValue() : '';
        //$label .= $this->isDraft() ? '[draft]' : $this->getNumber();
        $label .= !$this->getNumber() ? '[draft]' : $this->getNumber();

        return $label;
    }

    const DRAFT    = 0;
    const PENDING  = 1;
    const APPROVED = 2;
    const REJECTED = 3;

    public function getStatusString()
    {
        switch ($this->status) {
            case self::DRAFT;
                $status = 'draft';
                break;
            case self::REJECTED;
                $status = 'rejected';
                break;
            case self::APPROVED;
                $status = 'approved';
                break;
            case self::PENDING:
                $status = 'pending';
                break;
            default:
                $status = 'unknown';
                break;
        }
        return $status;
    }

    public function checkStatus()
    {
        if ($this->isDraft()) {
            $this->setStatus(Order::DRAFT);
        }

src/Siwapp/OrderBundle/Form/OrderType.php
<?php

namespace Siwapp\OrderBundle\Form;

use Siwapp\CoreBundle\Form\AbstractInvoiceType;
use Siwapp\OrderBundle\Entity\Order;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderType extends AbstractInvoiceType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

        $builder
            ->add('issue_date', DateType::class, [
                'widget' => 'single_text',
                'label' => 'form.issue_date',
                'translation_domain' => 'SiwappOrderBundle',
            ])
            ->add('sent_by_email', null, [
                'label' => 'form.sent_by_email',
                'translation_domain' => 'SiwappInvoiceBundle',
            ])
            ->add('imported', HiddenType::class, [
                'attr' => ['value' => '0'],
                'label' => false,
                'translation_domain' => 'SiwappOrderBundle',
            ])
            ->add('iban', HiddenType::class, [
                'label' => false,
            ])
            ->add('bic', HiddenType::class, [
                'label' => false,
            ])
            ->add('mandato', HiddenType::class, [
                'label' => false,
            ])
            ->add('fecha_mandato', DateType::class, [
                'label' => false,
                'attr' => array('style' => "display:none"),
            ])
        ;

        $choices = array(
            'order.pending' => Order::PENDING,
            'order.approved' => Order::APPROVED,
            'order.rejected' => Order::REJECTED
        );

        if ( $builder->getData()->isDraft() )
        {
            $choices = array_merge(array('' => Order::DRAFT), $choices);
        }

        //if (!$builder->getData()->isDraft()) {
        if ($builder->getData()->getNumber() > 0) {
            $builder->add('status', ChoiceType::class, [
                'label' => 'form.status',
                'translation_domain' => 'SiwappOrderBundle',
                'choices' => $choices,
            ]);
        }
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setRequired([
            'editing'
        ]);

        $resolver->setDefaults([
            'data_class' => 'Siwapp\OrderBundle\Entity\Order',
            'editing' => false,
        ]);
    }
}

src/Siwapp/OrderBundle/Resources/views/Order/edit.html.twig
{% extends "SiwappCoreBundle:AbstractInvoice:edit.html.twig" %}
{% trans_default_domain 'SiwappOrderBundle' %}


{% block page_messages %}
  {{ parent() }}

  {% if app.request.session.get('order_auto_print') %}
  <div class="alert alert-warning fade in js-hide">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <a href="{{ path('estimate_show_print', {'id': app.request.session.remove('order_auto_print')}) }}" class="js-auto-click">{% trans %}flash.no_js_order_print{% endtrans %}</a>
  </div>
  {% endif %}
{% endblock %}


{% block actionlink %}
<a href="{{ path('order_add') }}" class="btn btn-default btn-primary">
  <span class="glyphicon glyphicon-plus"></span>
  {% trans %}menu.order_add{% endtrans %}
</a>
{% endblock %}


{% block invoice_label %}
  <h2>{% trans %}order.order{% endtrans %} {{ entity.label() }}</h2>
  <ul id="invoice-like-status" class="list-unstyled">
    <li>
      <span class="label {{ entity.statusString }}">{{ ('order.' ~ entity.statusString)|trans }}</span>
    </li>
    <li>
      {% if entity.sentByEmail %}
      <span class="label notice">{% trans %}order.sent_by_email{% endtrans %}</span>
      {% else %}
      <span class="label">{% trans %}order.not_sent_by_email{% endtrans %}</span>
      {% endif %}
    </li>
  </ul>
{% endblock %}


{% block properties_form %}
  {{ form_row(form.series) }}
  {{ form_row(form.issue_date) }}
  {% if form.status is defined %}
  {{ form_row(form.status) }}
  {% endif %}
  {{ form_row(form.sent_by_email) }}
  {{ form_row(form.imported) }}
{% endblock %}

{% block form_actions %}
  <input type="submit" class="btn btn-default btn-primary" name="save" value="{% trans %}form.submit{% endtrans %}">
  {% if not entity.id or entity.isDraft() %}
  <input type="submit" class="btn btn-default" name="save_draft" value="{% trans %}form.submit_draft{% endtrans %}">
  {% endif %}
  {% if entity.isApproved() %}
  <input type="submit" class="btn btn-default" name="save_close" value="{% trans %}form.submit_close{% endtrans %}">
  {% endif %}

  {% if entity.id %}
  <input type="submit" class="btn btn-default btn-info" name="save_pdf" value="{% trans %}form.submit_pdf{% endtrans %}">
  <input type="submit" class="btn btn-default btn-info" name="save_print" value="{% trans %}form.submit_print{% endtrans %}">
  <input type="submit" class="btn btn-default btn-warning" name="save_email" value="{% trans %}form.submit_email{% endtrans %}">
  <input type="submit" class="btn btn-default btn-warning" name="save_generate" value="{% trans %}form.submit_generate{% endtrans %}">
  {% endif %}

  <div class="float-right">
    {% if entity.id %}
    <a class="btn btn-default btn-danger" href="{{ path('order_delete', {'id': entity.id}) }}">{% trans %}form.submit_delete{% endtrans %}</a>
    {% endif %}
  </div>
{% endblock %}


{% block javascripts %}
  {{ parent() }}

	<script type="text/javascript">

 	 	jQuery(function($) {

    		$(document).on('change', '.edit-item-row select, .edit-item-row input', function () {
      			updateInvoiceTotals('{{ path('order_form_totals') }}', $(this).parents('tr'));
    		});
  		});

 	 	$(document).ready(function () {
 	 		updateInvoiceTotals('{{ path('order_form_totals') }}', $('.edit-item-row select, .edit-item-row input').parents('tr'));
 	 	});

  	</script>
{% endblock %}

src/Siwapp/OrderBundle/Resources/views/Order/email.html.twig
{% extends "SiwappOrderBundle:Order:print.html.twig" %}

src/Siwapp/OrderBundle/Resources/views/Order/index.html.twig
{% extends "SiwappCoreBundle::base.html.twig" %}
{% trans_default_domain 'SiwappOrderBundle' %}

{% block actionlink %}
<a href="{{ path('order_add') }}" class="btn btn-default btn-primary">
  <span class="glyphicon glyphicon-plus"></span>
  {% trans %}menu.order_add{% endtrans %}
</a>
{% endblock %}

{% block searchform %}
  {% include "SiwappOrderBundle:Order:search.html.twig" with {'form': search_form} %}
{% endblock %}

{% block body %}
  <div id="invoices-latest-recurring-invoices">
    {% include "SiwappOrderBundle:Order:list.html.twig" %}
  </div>
{% endblock %}

src/Siwapp/OrderBundle/Resources/views/Order/list.html.twig
{% trans_default_domain 'SiwappOrderBundle' %}

<ul id="toolbar" class="table-actions list-inline list-unstyled">
  <li>
    <button type="submit" name="delete" class="btn btn-default btn-danger" title="{% trans %}list.bulk_delete{% endtrans %}"><span class="glyphicon glyphicon-trash"></span></button>
  </li>
  <li>
    <button type="submit" name="print" class="btn btn-default" title="{% trans %}list.bulk_print{% endtrans %}"><span class="glyphicon glyphicon-print"></span></button>
  </li>
  <li>
    <button type="submit" name="pdf" class="btn btn-default" title="{% trans %}list.bulk_pdf{% endtrans %}"><span class="glyphicon glyphicon-download-alt"></span></button>
  </li>
  <li>
    <button type="submit" name="email" class="btn btn-default" title="{% trans %}list.bulk_email{% endtrans %}"><span class="glyphicon glyphicon-envelope"></span></button>
  </li>
</ul>
<table class="table table-condensed table-striped align-middle" data-type="estimates">
  <thead>
    <tr>
      <th class="cell-size-tiny cell-align-center">
        <input type="checkbox" name="all" />
      </th>
      <th class="cell-size-medium">
        {{ knp_pagination_sortable(orders, 'list.series'|trans, ['i.number']) }}
      </th>
      <th>
        {{ knp_pagination_sortable(orders, 'list.customer_name'|trans, 'i.customer_name') }}
      </th>
      <th class="cell-size-medium">
        {{ knp_pagination_sortable(orders, 'list.issue_date'|trans, 'i.issue_date') }}
      </th>
      <th class="cell-size-small-medium cell-align-center">
        {{ knp_pagination_sortable(orders, 'list.status'|trans, 'i.status') }}
      </th>
      <th class="cell-size-medium cell-align-right">
        {{ knp_pagination_sortable(orders, 'list.gross_amount'|trans, 'i.gross_amount') }}
      </th>
    </tr>
  </thead>
  <tbody>
    {% if orders|length == 0 %}
      <tr>
        <td colspan="7">{% trans %}list.no_results{% endtrans %}</td>
      </tr>
    {% endif %}
    {% set total = 0 %}
    {% for key, entity in orders %}
      <tr data-link="{{ path('order_show', { 'id': entity.id }) }}">
        <td class="table-action cell-align-center no-link">
          {{ form_row(list_form.orders[key]) }}
        </td>
        <td class="cell-size-medium cell-align-center">{{ entity.series }}</td>
        <td>{{ entity.getCustomerName }}</td>
        <td>{{ entity.issueDate|localizeddate('short', 'none', app.request.locale) }}</td>
        <td class="cell-align-center">
          <span class="label {{ entity.statusString }}">{{ ('order.' ~ entity.statusString)|trans }}</span>
        </td>
        <td class="cell-align-right">{{ entity.grossAmount|localizedcurrency(currency, app.request.locale) }}</td>
      </tr>
      {% set total = total + entity.grossAmount %}
    {% endfor %}
  </tbody>
</table>
{{ form_end(list_form) }}
<div class="navigation">
    {{ knp_pagination_render(orders) }}
</div>

<div><h4 style="text-align: right">TOTAL :{{ total|localizedcurrency(currency, app.request.locale) }}</h4></div>

src/Siwapp/OrderBundle/Resources/views/Order/search.html.twig
{% trans_default_domain 'SiwappEstimateBundle' %}
{% set is_expanded = form.vars.value and (form.vars.value.customer is not null or form.vars.value.series is not null or form.vars.value.status is not null) %}

{{ form_start(form, {'attr': {'class': 'search form-inline'}}) }}

  <fieldset>

    {{ form_row(form.terms) }}
    {{ form_row(form.date_from) }}
    {{ form_row(form.date_to) }}

    <div class="form-group float-right btn-toolbar">
      <div class="btn-group">
        <button id="search-submit" type="submit" class="btn btn-default btn-primary">{% trans %}search.submit{% endtrans %}</button>
        <a href="#search-secondary" data-toggle="collapse" class="btn btn-default"{% if is_expanded %} aria-expanded="true"{% endif %}" aria-controls="search-secondary">
          {% trans %}search.advanced{% endtrans %}
        <span class="caret"></span>
        </a>
      </div>
      <div class="btn-group">
        <button id="search-reset" type="reset" class="btn btn-default btn-warning">{% trans %}search.reset{% endtrans %}</button>
      </div>
    </div>

  </fieldset>

  <fieldset id="search-secondary" class="collapse{% if is_expanded %} in{% endif %}">
      {{ form_row(form.status) }}
      {{ form_row(form.customer) }}
      {{ form_row(form.series) }}
  </fieldset>

{{ form_end(form) }}

src/Siwapp/OrderBundle/Resources/views/Order/show.html.twig
{% extends "SiwappCoreBundle:AbstractInvoice:show.html.twig" %}
{% trans_default_domain 'SiwappOrderBundle' %}

{% block actionlink %}
<a href="{{ path('order_add') }}" class="btn btn-default btn-primary">
  <span class="glyphicon glyphicon-plus"></span>
  {% trans %}menu.order_add{% endtrans %}
</a>
{% endblock %}


{% block invoice_actions %}
  <ul class="entity-actions list-inline float-right">
    <li><a class="btn btn-default btn-info" href="{{ path('order_show_pdf', {'id': entity.id}) }}"><span class="glyphicon glyphicon-download-alt"></span> {% trans %}show.pdf{% endtrans %}</a></li>
    <li><a class="btn btn-default btn-info" href="{{ path('order_show_print', {'id': entity.id}) }}" target="_blank"><span class="glyphicon glyphicon-print"></span> {% trans %}show.print{% endtrans %}</a></li>
    <li><form action="{{ path('order_email', {'id': entity.id}) }}" method="post">
      <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
      <button type="submit" class="btn btn-default btn-warning"><span class="glyphicon glyphicon-envelope"></span> {%trans %}show.email{% endtrans %}</button>
      </form>
    </li>
    <li><form action="{{ path('order_generate_estimate', {'id': entity.id}) }}" method="post">
      <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
      <button type="submit" class="btn btn-default btn-warning"><span class="glyphicon glyphicon-file"></span> {% trans %}show.generate_estimate{% endtrans %}</button>
      </form></li>
  </ul>
{% endblock %}


{% block invoice_label %}
  <h2>Estimate {{ entity.label() }}</h2>
  <ul class="list-inline list-unstyled">
    <li>
      <span class="label {{ entity.statusString }}">{{ ('order.' ~ entity.statusString)|trans }}</span>
    </li>
    <li>
      {% if entity.sentByEmail %}
      <span class="label notice">{% trans %}order.sent_by_email{% endtrans %}</span>
      {% else %}
      <span class="label">{% trans %}order.not_sent_by_email{% endtrans %}</span>
      {% endif %}
    </li>
  </ul>
{% endblock %}


{% block properties %}
  <div class="col-md-12">
    <label>{% trans %}show.series{% endtrans %}:</label>
    {{ entity.series }}
  </div>
  <div class="col-md-12">
    <label>{% trans %}show.issue_date{% endtrans %}:</label>
    {{ entity.issue_date|localizeddate('medium', 'none', app.request.locale) }}
  </div>
{% endblock %}


{% block invoice_edit_actions %}
  <ul class="list-inline float-right">
    <li><a class="btn btn-default" href="{{ path('order_edit', {'id': entity.id}) }}"><span class="glyphicon glyphicon-pencil"></span> {% trans %}show.edit{% endtrans %}</a></li>
    <li><a class="btn btn-default btn-danger" href="{{ path('order_delete', {'id': entity.id}) }}"><span class="glyphicon glyphicon-trash"></span> {% trans %}show.delete{% endtrans %}</a></li>
  </ul>
{% endblock %}